version: '3.8'

services:
  backend:
    image: ghcr.io/ankitmor2106/resumate:latest
    container_name: resuhive_backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres.xpyadeetgcozdpdgkypz:ankit%40resumate@aws-1-ap-south-1.pooler.supabase.com:5432/postgres
      - JWT_SECRET=super_secret_jwt_key_please_change
      - JWT_REFRESH_SECRET=super_secret_refresh_key_please_change
      - GEMINI_API_KEY=dummy_gemini_key_for_startup
      - FRONTEND_URL=https://your-vercel-frontend-url.vercel.app
      - S3_BUCKET=your_s3_bucket
      - AWS_REGION=your_aws_region
      - AWS_ACCESS_KEY_ID=your_access_key
      - AWS_SECRET_ACCESS_KEY=your_secret_key
